name : Postman Collection WorkFlow

on: 
  push:
    branches: [main]
  workflow_dispatch: 
  schedule: 
    - cron: 30 02 * * * # 8 AM IST Every day
    - cron: 00 14 * * * # 7:30 PM IST Every day
    - cron: 00 06 * * 1-5 # 6 AM IST Mon- Fri

jobs: 
  run-postman-test: 
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v6-beta

      - name: Install node.js and npm
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'

      - name: install newman and html-extra globally
        run: |
             npm install -g newman 
             npm install -g newman-reporter-htmlextra

      - name: Run the postman collection with newman
        run: |
             newman run 'Inwarranty-flow Collection_CLI.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testdata.csv \
             -r cli,htmlextra

      - name: Newman Report
        uses: actions/upload-artifact@v5.0.0
        with:
          name: Newman Report
          path: newman/*.html
        

       
    
